@localhost = http://localhost:3000
@adminToken = Token 219be80504a7fcac11d5fb2e2aaada9d0c6be6d15b2497241a5f2d262012043d

###
get {{localhost}}/api/users

###
post {{localhost}}/api/users
Content-Type: application/json
Accept-Language: en

{
    "name" : "hadi",
    "email" : "dd@bla.com"
}

###
post {{localhost}}/api/posts
Content-Type: application/json
Accept-Language: en

{
    "title" : "this is post",
    "description": "new description1"
}

###
put {{localhost}}/api/posts/6131d71b6a82f0db0d40ee78
Content-Type: application/json
Accept-Language: en
Authorization: {{adminToken}}

{
    "title" : 112312312,
    "description": "new description1"    
}

###
get {{localhost}}/api/posts

###
get {{localhost}}/api/posts/6131d76dd4c8816581e4908b
Authorization: {{adminToken}}
